; auto-generated by translate_6502.py
; full pipeline: cc65 -> translate_6502 -> ocpu_asm

.page 0
main:
    LDA #$00                ; 6502: LDA #$00
    STA $40                 ; 6502: STA $40
    LDA $40                 ; 6502: INC $40  (microcode 1/3)
    ADC #$01                ; (microcode 2/3)
    STA $40                 ; (microcode 3/3)
    HLT                     ; 6502: BRK  (BRK -> HLT)
