; auto-generated by translate_6502.py
; full pipeline: cc65 -> translate_6502 -> ocpu_asm
    .data $0040            ; segment DATA
    .byte $01
    .byte $02
    .byte $03
    .byte $04
    .data $0080            ; segment BSS
    .byte $00

.page 0
_main:
    LDA #$00                ; 6502: lda #$00
    STA $80                 ; 6502: sta $0080
    LDA $40                 ; 6502: lda $0040
    CLC                     ; 6502: clc
    ADC $80                 ; 6502: adc $0080
    STA $80                 ; 6502: sta $0080
    LDA $41                 ; 6502: lda $0041
    CLC                     ; 6502: clc

.page 1
    ADC $80                 ; 6502: adc $0080
    STA $80                 ; 6502: sta $0080
    LDA $42                 ; 6502: lda $0042
    CLC                     ; 6502: clc
    ADC $80                 ; 6502: adc $0080
    STA $80                 ; 6502: sta $0080
    LDA $43                 ; 6502: lda $0043
    CLC                     ; 6502: clc

.page 2
    ADC $80                 ; 6502: adc $0080
    STA $80                 ; 6502: sta $0080
    HLT                     ; 6502: rts (rewritten -> HLT)
