;
; File generated by cc65 v 2.19 - Git b4e66ea
;
	.fopt		compiler,"cc65 v 2.19 - Git b4e66ea"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_arr
	.export		_sum
	.export		_main

.segment	"DATA"

_arr:
	.byte	$01
	.byte	$02
	.byte	$03
	.byte	$04

.segment	"BSS"

_sum:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$00
	sta     _sum
	lda     _arr
	clc
	adc     _sum
	sta     _sum
	lda     _arr+1
	clc
	adc     _sum
	sta     _sum
	lda     _arr+2
	clc
	adc     _sum
	sta     _sum
	lda     _arr+3
	clc
	adc     _sum
	sta     _sum
	rts

.endproc

