; auto-generated by translate_6502.py
; full pipeline: cc65 -> translate_6502 -> ocpu_asm
    .data $0040            ; segment DATA
    .byte $0C
    .byte $2C
    .byte $5B
    .byte $03
    .byte $4D
    .byte $12
    .byte $C8
    .byte $05
    .byte $42
    .byte $63
    .byte $65
    .byte $2A
    .byte $58
    .byte $01
    .byte $FA
    .byte $11
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .data $0080            ; segment BSS
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00

.page 0
_main:
    LDA #$00                ; 6502: lda #$00
    STA $80                 ; 6502: sta $0080
    STA $81                 ; 6502: sta $0081
    STA $82                 ; 6502: sta $0082

.page 1
    STA $83                 ; 6502: sta $0083
    STA $88                 ; 6502: sta $0088
    STA $89                 ; 6502: sta $0089
    STA $8a                 ; 6502: sta $008a

.page 2
    STA $8b                 ; 6502: sta $008b
    STA $8c                 ; 6502: sta $008c
    STA $86                 ; 6502: sta $0086
    LDA #$FF                ; 6502: lda #$FF

.page 3
    STA $87                 ; 6502: sta $0087
    LDA $40                 ; 6502: lda $0040
    STA $8d                 ; 6502: sta $008d
    LDA $41                 ; 6502: lda $0041

.page 4
    STA $8e                 ; 6502: sta $008e
    LDA $42                 ; 6502: lda $0042
    STA $8f                 ; 6502: sta $008f
    LDA $43                 ; 6502: lda $0043

.page 5
    STA $90                 ; 6502: sta $0090
    LDA $44                 ; 6502: lda $0044
    STA $91                 ; 6502: sta $0091
    LDA $45                 ; 6502: lda $0045

.page 6
    STA $92                 ; 6502: sta $0092
    LDA $46                 ; 6502: lda $0046
    STA $93                 ; 6502: sta $0093
    LDA $47                 ; 6502: lda $0047

.page 7
    STA $94                 ; 6502: sta $0094
    LDA $80                 ; 6502: lda $0080
    CLC                     ; 6502: clc
    ADC $8d                 ; 6502: adc $008d

.page 8
    STA $80                 ; 6502: sta $0080
    CLC                     ; 6502: clc
    ADC $8e                 ; 6502: adc $008e
    STA $80                 ; 6502: sta $0080

.page 9
    CLC                     ; 6502: clc
    ADC $8f                 ; 6502: adc $008f
    STA $80                 ; 6502: sta $0080
    CLC                     ; 6502: clc

.page 10
    ADC $90                 ; 6502: adc $0090
    STA $80                 ; 6502: sta $0080
    CLC                     ; 6502: clc
    ADC $91                 ; 6502: adc $0091

.page 11
    STA $80                 ; 6502: sta $0080
    CLC                     ; 6502: clc
    ADC $92                 ; 6502: adc $0092
    STA $80                 ; 6502: sta $0080

.page 12
    CLC                     ; 6502: clc
    ADC $93                 ; 6502: adc $0093
    STA $80                 ; 6502: sta $0080
    CLC                     ; 6502: clc

.page 13
    ADC $94                 ; 6502: adc $0094
    STA $80                 ; 6502: sta $0080
    EOR $48                 ; 6502: eor $0048
    STA $80                 ; 6502: sta $0080

.page 14
    EOR $49                 ; 6502: eor $0049
    STA $80                 ; 6502: sta $0080
    EOR $4a                 ; 6502: eor $004a
    STA $80                 ; 6502: sta $0080

.page 15
    EOR $4b                 ; 6502: eor $004b
    STA $80                 ; 6502: sta $0080
    EOR $4c                 ; 6502: eor $004c
    STA $80                 ; 6502: sta $0080

.page 16
    EOR $4d                 ; 6502: eor $004d
    STA $80                 ; 6502: sta $0080
    EOR $4e                 ; 6502: eor $004e
    STA $80                 ; 6502: sta $0080

.page 17
    EOR $4f                 ; 6502: eor $004f
    STA $80                 ; 6502: sta $0080
    LDA $8d                 ; 6502: lda $008d
    CMP $86                 ; 6502: cmp $0086

.page 18
    BCC L004F               ; 6502: bcc L004F
    BEQ L004F               ; 6502: beq L004F
    STA $86                 ; 6502: sta $0086
L004F:
    LDA $8e                 ; 6502: lda $008e

.page 19
    CMP $86                 ; 6502: cmp $0086
    BCS __brfix_4f     ; (auto-inverted, cross-page BCC -> L0050)
    FARJMP $15        ; (auto-bridge)
__brfix_4f:
    NOP        ; no room for branch bridge

.page 20
    BNE __brfix_50     ; (auto-inverted, cross-page BEQ -> L0050)
    FARJMP $15        ; (auto-bridge)
__brfix_50:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0

.page 21
L0050:
    LDA $8f                 ; 6502: lda $008f
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 22
    BCS __brfix_55     ; (auto-inverted, cross-page BCC -> L0051)
    FARJMP $18        ; (auto-bridge)
__brfix_55:
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 23
    BNE __brfix_56     ; (auto-inverted, cross-page BEQ -> L0051)
    FARJMP $18        ; (auto-bridge)
__brfix_56:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0

.page 24
L0051:
    LDA $90                 ; 6502: lda $0090
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 25
    BCS __brfix_5b     ; (auto-inverted, cross-page BCC -> L0052)
    FARJMP $1b        ; (auto-bridge)
__brfix_5b:
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 26
    BNE __brfix_5c     ; (auto-inverted, cross-page BEQ -> L0052)
    FARJMP $1b        ; (auto-bridge)
__brfix_5c:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0

.page 27
L0052:
    LDA $91                 ; 6502: lda $0091
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 28
    BCS __brfix_61     ; (auto-inverted, cross-page BCC -> L0053)
    FARJMP $1e        ; (auto-bridge)
__brfix_61:
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 29
    BNE __brfix_62     ; (auto-inverted, cross-page BEQ -> L0053)
    FARJMP $1e        ; (auto-bridge)
__brfix_62:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0

.page 30
L0053:
    LDA $92                 ; 6502: lda $0092
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 31
    BCS __brfix_67     ; (auto-inverted, cross-page BCC -> L0054)
    FARJMP $21        ; (auto-bridge)
__brfix_67:
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 32
    BNE __brfix_68     ; (auto-inverted, cross-page BEQ -> L0054)
    FARJMP $21        ; (auto-bridge)
__brfix_68:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0

.page 33
L0054:
    LDA $93                 ; 6502: lda $0093
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 34
    BCS __brfix_6d     ; (auto-inverted, cross-page BCC -> L0055)
    FARJMP $24        ; (auto-bridge)
__brfix_6d:
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 35
    BNE __brfix_6e     ; (auto-inverted, cross-page BEQ -> L0055)
    FARJMP $24        ; (auto-bridge)
__brfix_6e:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0

.page 36
L0055:
    LDA $94                 ; 6502: lda $0094
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 37
    BCS __brfix_73     ; (auto-inverted, cross-page BCC -> L0056)
    FARJMP $27        ; (auto-bridge)
__brfix_73:
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 38
    BNE __brfix_74     ; (auto-inverted, cross-page BEQ -> L0056)
    FARJMP $27        ; (auto-bridge)
__brfix_74:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0

.page 39
L0056:
    LDA $48                 ; 6502: lda $0048
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 40
    BCS __brfix_79     ; (auto-inverted, cross-page BCC -> L0057)
    FARJMP $2a        ; (auto-bridge)
__brfix_79:
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 41
    BNE __brfix_7a     ; (auto-inverted, cross-page BEQ -> L0057)
    FARJMP $2a        ; (auto-bridge)
__brfix_7a:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0

.page 42
L0057:
    LDA $49                 ; 6502: lda $0049
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 43
    BCS __brfix_7f     ; (auto-inverted, cross-page BCC -> L0058)
    FARJMP $2d        ; (auto-bridge)
__brfix_7f:
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 44
    BNE __brfix_80     ; (auto-inverted, cross-page BEQ -> L0058)
    FARJMP $2d        ; (auto-bridge)
__brfix_80:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0

.page 45
L0058:
    LDA $4a                 ; 6502: lda $004a
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 46
    BCS __brfix_85     ; (auto-inverted, cross-page BCC -> L0059)
    FARJMP $30        ; (auto-bridge)
__brfix_85:
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 47
    BNE __brfix_86     ; (auto-inverted, cross-page BEQ -> L0059)
    FARJMP $30        ; (auto-bridge)
__brfix_86:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0

.page 48
L0059:
    LDA $4b                 ; 6502: lda $004b
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 49
    BCS __brfix_8b     ; (auto-inverted, cross-page BCC -> L005A)
    FARJMP $33        ; (auto-bridge)
__brfix_8b:
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 50
    BNE __brfix_8c     ; (auto-inverted, cross-page BEQ -> L005A)
    FARJMP $33        ; (auto-bridge)
__brfix_8c:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0

.page 51
L005A:
    LDA $4c                 ; 6502: lda $004c
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 52
    BCS __brfix_91     ; (auto-inverted, cross-page BCC -> L005B)
    FARJMP $36        ; (auto-bridge)
__brfix_91:
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 53
    BNE __brfix_92     ; (auto-inverted, cross-page BEQ -> L005B)
    FARJMP $36        ; (auto-bridge)
__brfix_92:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0

.page 54
L005B:
    LDA $4d                 ; 6502: lda $004d
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 55
    BCS __brfix_97     ; (auto-inverted, cross-page BCC -> L005C)
    FARJMP $39        ; (auto-bridge)
__brfix_97:
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 56
    BNE __brfix_98     ; (auto-inverted, cross-page BEQ -> L005C)
    FARJMP $39        ; (auto-bridge)
__brfix_98:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0

.page 57
L005C:
    LDA $4e                 ; 6502: lda $004e
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 58
    BCS __brfix_9d     ; (auto-inverted, cross-page BCC -> L005D)
    FARJMP $3c        ; (auto-bridge)
__brfix_9d:
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 59
    BNE __brfix_9e     ; (auto-inverted, cross-page BEQ -> L005D)
    FARJMP $3c        ; (auto-bridge)
__brfix_9e:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0

.page 60
L005D:
    LDA $4f                 ; 6502: lda $004f
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 61
    BCS __brfix_a3     ; (auto-inverted, cross-page BCC -> L005E)
    FARJMP $3f        ; (auto-bridge)
__brfix_a3:
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 62
    BNE __brfix_a4     ; (auto-inverted, cross-page BEQ -> L005E)
    FARJMP $3f        ; (auto-bridge)
__brfix_a4:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0

.page 63
L005E:
    LDA $8d                 ; 6502: lda $008d
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 64
    BCC __brfix_a9     ; (auto-inverted, cross-page BCS -> L005F)
    FARJMP $41        ; (auto-bridge)
__brfix_a9:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0

.page 65
L005F:
    LDA $8e                 ; 6502: lda $008e
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 66
    BCC __brfix_ae     ; (auto-inverted, cross-page BCS -> L0060)
    FARJMP $43        ; (auto-bridge)
__brfix_ae:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0

.page 67
L0060:
    LDA $8f                 ; 6502: lda $008f
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 68
    BCC __brfix_b3     ; (auto-inverted, cross-page BCS -> L0061)
    FARJMP $45        ; (auto-bridge)
__brfix_b3:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0

.page 69
L0061:
    LDA $90                 ; 6502: lda $0090
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 70
    BCC __brfix_b8     ; (auto-inverted, cross-page BCS -> L0062)
    FARJMP $47        ; (auto-bridge)
__brfix_b8:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0

.page 71
L0062:
    LDA $91                 ; 6502: lda $0091
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 72
    BCC __brfix_bd     ; (auto-inverted, cross-page BCS -> L0063)
    FARJMP $49        ; (auto-bridge)
__brfix_bd:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0

.page 73
L0063:
    LDA $92                 ; 6502: lda $0092
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 74
    BCC __brfix_c2     ; (auto-inverted, cross-page BCS -> L0064)
    FARJMP $4b        ; (auto-bridge)
__brfix_c2:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0

.page 75
L0064:
    LDA $93                 ; 6502: lda $0093
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 76
    BCC __brfix_c7     ; (auto-inverted, cross-page BCS -> L0065)
    FARJMP $4d        ; (auto-bridge)
__brfix_c7:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0

.page 77
L0065:
    LDA $94                 ; 6502: lda $0094
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 78
    BCC __brfix_cc     ; (auto-inverted, cross-page BCS -> L0066)
    FARJMP $4f        ; (auto-bridge)
__brfix_cc:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0

.page 79
L0066:
    LDA $48                 ; 6502: lda $0048
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 80
    BCC __brfix_d1     ; (auto-inverted, cross-page BCS -> L0067)
    FARJMP $51        ; (auto-bridge)
__brfix_d1:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0

.page 81
L0067:
    LDA $49                 ; 6502: lda $0049
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 82
    BCC __brfix_d6     ; (auto-inverted, cross-page BCS -> L0068)
    FARJMP $53        ; (auto-bridge)
__brfix_d6:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0

.page 83
L0068:
    LDA $4a                 ; 6502: lda $004a
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 84
    BCC __brfix_db     ; (auto-inverted, cross-page BCS -> L0069)
    FARJMP $55        ; (auto-bridge)
__brfix_db:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0

.page 85
L0069:
    LDA $4b                 ; 6502: lda $004b
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 86
    BCC __brfix_e0     ; (auto-inverted, cross-page BCS -> L006A)
    FARJMP $57        ; (auto-bridge)
__brfix_e0:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0

.page 87
L006A:
    LDA $4c                 ; 6502: lda $004c
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 88
    BCC __brfix_e5     ; (auto-inverted, cross-page BCS -> L006B)
    FARJMP $59        ; (auto-bridge)
__brfix_e5:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0

.page 89
L006B:
    LDA $4d                 ; 6502: lda $004d
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 90
    BCC __brfix_ea     ; (auto-inverted, cross-page BCS -> L006C)
    FARJMP $5b        ; (auto-bridge)
__brfix_ea:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0

.page 91
L006C:
    LDA $4e                 ; 6502: lda $004e
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 92
    BCC __brfix_ef     ; (auto-inverted, cross-page BCS -> L006D)
    FARJMP $5d        ; (auto-bridge)
__brfix_ef:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0

.page 93
L006D:
    LDA $4f                 ; 6502: lda $004f
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 94
    BCC __brfix_f4     ; (auto-inverted, cross-page BCS -> L006E)
    FARJMP $5f        ; (auto-bridge)
__brfix_f4:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0

.page 95
L006E:
    LDA $8d                 ; 6502: lda $008d
    CMP #$65                ; 6502: cmp #$65
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 96
    BCS __brfix_f9     ; (auto-inverted, cross-page BCC -> L006F)
    FARJMP $62        ; (auto-bridge)
__brfix_f9:
    LDA $81                 ; 6502: lda $0081
    CLC                     ; 6502: clc

.page 97
    ADC #$01                ; 6502: adc #$01
    STA $81                 ; 6502: sta $0081
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 98
L006F:
    LDA $8e                 ; 6502: lda $008e
    CMP #$65                ; 6502: cmp #$65
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 99
    BCS __brfix_101     ; (auto-inverted, cross-page BCC -> L0070)
    FARJMP $65        ; (auto-bridge)
__brfix_101:
    LDA $81                 ; 6502: lda $0081
    CLC                     ; 6502: clc

.page 100
    ADC #$01                ; 6502: adc #$01
    STA $81                 ; 6502: sta $0081
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 101
L0070:
    LDA $8f                 ; 6502: lda $008f
    CMP #$65                ; 6502: cmp #$65
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 102
    BCS __brfix_109     ; (auto-inverted, cross-page BCC -> L0071)
    FARJMP $68        ; (auto-bridge)
__brfix_109:
    LDA $81                 ; 6502: lda $0081
    CLC                     ; 6502: clc

.page 103
    ADC #$01                ; 6502: adc #$01
    STA $81                 ; 6502: sta $0081
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 104
L0071:
    LDA $90                 ; 6502: lda $0090
    CMP #$65                ; 6502: cmp #$65
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 105
    BCS __brfix_111     ; (auto-inverted, cross-page BCC -> L0072)
    FARJMP $6b        ; (auto-bridge)
__brfix_111:
    LDA $81                 ; 6502: lda $0081
    CLC                     ; 6502: clc

.page 106
    ADC #$01                ; 6502: adc #$01
    STA $81                 ; 6502: sta $0081
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 107
L0072:
    LDA $4a                 ; 6502: lda $004a
    CMP #$79                ; 6502: cmp #$79
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 108
    BCS __brfix_119     ; (auto-inverted, cross-page BCC -> L0073)
    FARJMP $6e        ; (auto-bridge)
__brfix_119:
    LDA $81                 ; 6502: lda $0081
    CLC                     ; 6502: clc

.page 109
    ADC #$01                ; 6502: adc #$01
    STA $81                 ; 6502: sta $0081
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 110
L0073:
    LDA $4e                 ; 6502: lda $004e
    CMP #$C9                ; 6502: cmp #$C9
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 111
    BCS __brfix_121     ; (auto-inverted, cross-page BCC -> L0074)
    FARJMP $71        ; (auto-bridge)
__brfix_121:
    LDA $82                 ; 6502: lda $0082
    CLC                     ; 6502: clc

.page 112
    ADC #$01                ; 6502: adc #$01
    STA $82                 ; 6502: sta $0082
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 113
L0074:
    LDA $46                 ; 6502: lda $0046
    CMP #$B5                ; 6502: cmp #$B5
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 114
    BCS __brfix_129     ; (auto-inverted, cross-page BCC -> L0075)
    FARJMP $75        ; (auto-bridge)
__brfix_129:
    LDA $82                 ; 6502: lda $0082
    CLC                     ; 6502: clc

.page 115
    ADC #$01                ; 6502: adc #$01
    STA $82                 ; 6502: sta $0082
    LDA $83                 ; 6502: lda $0083
    ORA #$01                ; 6502: ora #$01

.page 116
    FARJMP $76        ; (rewritten from JMP L004B; cross-page)
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 117
L0075:
    LDA $83                 ; 6502: lda $0083
    EOR #$02                ; 6502: eor #$02
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 118
L004B:
    STA $83                 ; 6502: sta $0083
    LDA $86                 ; 6502: lda $0086
    CMP #$F1                ; 6502: cmp #$F1
    NOP        ; no room for branch bridge

.page 119
    BCS __brfix_138     ; (auto-inverted, cross-page BCC -> L0076)
    FARJMP $79        ; (auto-bridge)
__brfix_138:
    LDA $8c                 ; 6502: lda $008c
    ORA #$80                ; 6502: ora #$80

.page 120
    FARJMP $7a        ; (rewritten from JMP L004C; cross-page)
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 121
L0076:
    LDA $8c                 ; 6502: lda $008c
    ORA #$01                ; 6502: ora #$01
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 122
L004C:
    STA $8c                 ; 6502: sta $008c
    LDA $87                 ; 6502: lda $0087
    CMP #$05                ; 6502: cmp #$05
    NOP        ; no room for branch bridge

.page 123
    BCC __brfix_143     ; (auto-inverted, cross-page BCS -> L0077)
    FARJMP $7d        ; (auto-bridge)
__brfix_143:
    LDA $8c                 ; 6502: lda $008c
    ORA #$40                ; 6502: ora #$40

.page 124
    STA $8c                 ; 6502: sta $008c
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 125
L0077:
    LDA $89                 ; 6502: lda $0089
    EOR $40                 ; 6502: eor $0040
    STA $89                 ; 6502: sta $0089
    EOR $41                 ; 6502: eor $0041

.page 126
    STA $89                 ; 6502: sta $0089
    EOR $42                 ; 6502: eor $0042
    STA $89                 ; 6502: sta $0089
    EOR $43                 ; 6502: eor $0043

.page 127
    STA $89                 ; 6502: sta $0089
    EOR $44                 ; 6502: eor $0044
    STA $89                 ; 6502: sta $0089
    EOR $45                 ; 6502: eor $0045

.page 128
    STA $89                 ; 6502: sta $0089
    EOR $46                 ; 6502: eor $0046
    STA $89                 ; 6502: sta $0089
    EOR $47                 ; 6502: eor $0047

.page 129
    STA $89                 ; 6502: sta $0089
    LDA #$00                ; 6502: lda #$00
    STA $88                 ; 6502: sta $0088
    CLC                     ; 6502: clc

.page 130
    LDA $40                 ; 6502: lda $0040
    STA $88                 ; 6502: sta $0088
    CLC                     ; 6502: clc
    ADC $41                 ; 6502: adc $0041

.page 131
    STA $88                 ; 6502: sta $0088
    CLC                     ; 6502: clc
    ADC $42                 ; 6502: adc $0042
    STA $88                 ; 6502: sta $0088

.page 132
    CLC                     ; 6502: clc
    ADC $43                 ; 6502: adc $0043
    STA $88                 ; 6502: sta $0088
    CLC                     ; 6502: clc

.page 133
    ADC $44                 ; 6502: adc $0044
    STA $88                 ; 6502: sta $0088
    CLC                     ; 6502: clc
    ADC $45                 ; 6502: adc $0045

.page 134
    STA $88                 ; 6502: sta $0088
    CLC                     ; 6502: clc
    ADC $46                 ; 6502: adc $0046
    STA $88                 ; 6502: sta $0088

.page 135
    CLC                     ; 6502: clc
    ADC $47                 ; 6502: adc $0047
    STA $88                 ; 6502: sta $0088
    CLC                     ; 6502: clc

.page 136
    ADC #$08                ; 6502: adc #$08
    STA $88                 ; 6502: sta $0088
    LDA $80                 ; 6502: lda $0080
    STA $50                 ; 6502: sta $0050

.page 137
    LDA $81                 ; 6502: lda $0081
    STA $51                 ; 6502: sta $0051
    LDA $82                 ; 6502: lda $0082
    STA $52                 ; 6502: sta $0052

.page 138
    LDA $86                 ; 6502: lda $0086
    STA $53                 ; 6502: sta $0053
    LDA $87                 ; 6502: lda $0087
    STA $54                 ; 6502: sta $0054

.page 139
    LDA $89                 ; 6502: lda $0089
    STA $55                 ; 6502: sta $0055
    LDA $88                 ; 6502: lda $0088
    STA $56                 ; 6502: sta $0056

.page 140
    LDA $8c                 ; 6502: lda $008c
    STA $57                 ; 6502: sta $0057
    LDA $40                 ; 6502: lda $0040
    EOR $80                 ; 6502: eor $0080

.page 141
    STA $58                 ; 6502: sta $0058
    LDA $41                 ; 6502: lda $0041
    EOR $80                 ; 6502: eor $0080
    STA $59                 ; 6502: sta $0059

.page 142
    LDA $42                 ; 6502: lda $0042
    EOR $80                 ; 6502: eor $0080
    STA $5a                 ; 6502: sta $005a
    LDA $43                 ; 6502: lda $0043

.page 143
    EOR $80                 ; 6502: eor $0080
    STA $5b                 ; 6502: sta $005b
    LDA $44                 ; 6502: lda $0044
    CLC                     ; 6502: clc

.page 144
    ADC $81                 ; 6502: adc $0081
    STA $5c                 ; 6502: sta $005c
    LDA $45                 ; 6502: lda $0045
    CLC                     ; 6502: clc

.page 145
    ADC $81                 ; 6502: adc $0081
    STA $5d                 ; 6502: sta $005d
    LDA $46                 ; 6502: lda $0046
    CLC                     ; 6502: clc

.page 146
    ADC $81                 ; 6502: adc $0081
    STA $5e                 ; 6502: sta $005e
    LDA $47                 ; 6502: lda $0047
    CLC                     ; 6502: clc

.page 147
    ADC $81                 ; 6502: adc $0081
    STA $5f                 ; 6502: sta $005f
    LDA $48                 ; 6502: lda $0048
    ORA $83                 ; 6502: ora $0083

.page 148
    STA $60                 ; 6502: sta $0060
    LDA $49                 ; 6502: lda $0049
    ORA $83                 ; 6502: ora $0083
    STA $61                 ; 6502: sta $0061

.page 149
    LDA $4a                 ; 6502: lda $004a
    ORA $83                 ; 6502: ora $0083
    STA $62                 ; 6502: sta $0062
    LDA $4b                 ; 6502: lda $004b

.page 150
    ORA $83                 ; 6502: ora $0083
    STA $63                 ; 6502: sta $0063
    LDA $4c                 ; 6502: lda $004c
    AND #$7F                ; 6502: and #$7F

.page 151
    STA $64                 ; 6502: sta $0064
    LDA $4d                 ; 6502: lda $004d
    AND #$7F                ; 6502: and #$7F
    STA $65                 ; 6502: sta $0065

.page 152
    LDA $4e                 ; 6502: lda $004e
    AND #$7F                ; 6502: and #$7F
    STA $66                 ; 6502: sta $0066
    LDA $4f                 ; 6502: lda $004f

.page 153
    AND #$7F                ; 6502: and #$7F
    STA $67                 ; 6502: sta $0067
    LDA $50                 ; 6502: lda $0050
    EOR $58                 ; 6502: eor $0058

.page 154
    STA $68                 ; 6502: sta $0068
    LDA $51                 ; 6502: lda $0051
    EOR $59                 ; 6502: eor $0059
    STA $69                 ; 6502: sta $0069

.page 155
    LDA $52                 ; 6502: lda $0052
    EOR $5a                 ; 6502: eor $005a
    STA $6a                 ; 6502: sta $006a
    LDA $53                 ; 6502: lda $0053

.page 156
    EOR $5b                 ; 6502: eor $005b
    STA $6b                 ; 6502: sta $006b
    LDA $54                 ; 6502: lda $0054
    CLC                     ; 6502: clc

.page 157
    ADC $5c                 ; 6502: adc $005c
    STA $6c                 ; 6502: sta $006c
    LDA $55                 ; 6502: lda $0055
    CLC                     ; 6502: clc

.page 158
    ADC $5d                 ; 6502: adc $005d
    STA $6d                 ; 6502: sta $006d
    LDA $56                 ; 6502: lda $0056
    CLC                     ; 6502: clc

.page 159
    ADC $5e                 ; 6502: adc $005e
    STA $6e                 ; 6502: sta $006e
    LDA $57                 ; 6502: lda $0057
    CLC                     ; 6502: clc

.page 160
    ADC $5f                 ; 6502: adc $005f
    STA $6f                 ; 6502: sta $006f
    LDA #$00                ; 6502: lda #$00
    STA $8a                 ; 6502: sta $008a

.page 161
    LDA $82                 ; 6502: lda $0082
    BNE __brfix_1d9     ; (auto-inverted, cross-page BEQ -> L0078)
    FARJMP $a3        ; (auto-bridge)
__brfix_1d9:
    LDA $8a                 ; 6502: lda $008a

.page 162
    ORA #$80                ; 6502: ora #$80
    FARJMP $a4        ; (rewritten from JMP L004D; cross-page)
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 163
L0078:
    LDA $8a                 ; 6502: lda $008a
    ORA #$01                ; 6502: ora #$01
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 164
L004D:
    STA $8a                 ; 6502: sta $008a
    LDA $81                 ; 6502: lda $0081
    CMP #$03                ; 6502: cmp #$03
    NOP        ; no room for branch bridge

.page 165
    BCS __brfix_1e4     ; (auto-inverted, cross-page BCC -> L0079)
    FARJMP $a7        ; (auto-bridge)
__brfix_1e4:
    LDA $8a                 ; 6502: lda $008a
    ORA #$40                ; 6502: ora #$40

.page 166
    STA $8a                 ; 6502: sta $008a
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 167
L0079:
    LDA $80                 ; 6502: lda $0080
    BEQ __brfix_1ea     ; (auto-inverted, cross-page BNE -> L007A)
    FARJMP $a9        ; (auto-bridge)
__brfix_1ea:
    LDA $8a                 ; 6502: lda $008a

.page 168
    ORA #$20                ; 6502: ora #$20
    FARJMP $aa        ; (rewritten from JMP L004E; cross-page)
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 169
L007A:
    LDA $8a                 ; 6502: lda $008a
    EOR #$04                ; 6502: eor #$04
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 170
L004E:
    STA $8a                 ; 6502: sta $008a
    LDA #$00                ; 6502: lda #$00
    STA $8b                 ; 6502: sta $008b
    CLC                     ; 6502: clc

.page 171
    LDA #$01                ; 6502: lda #$01
    STA $8b                 ; 6502: sta $008b
    CLC                     ; 6502: clc
    ADC #$01                ; 6502: adc #$01

.page 172
    STA $8b                 ; 6502: sta $008b
    CLC                     ; 6502: clc
    ADC #$01                ; 6502: adc #$01
    STA $8b                 ; 6502: sta $008b

.page 173
    CLC                     ; 6502: clc
    ADC #$01                ; 6502: adc #$01
    STA $8b                 ; 6502: sta $008b
    CLC                     ; 6502: clc

.page 174
    ADC #$01                ; 6502: adc #$01
    STA $8b                 ; 6502: sta $008b
    CLC                     ; 6502: clc
    ADC #$01                ; 6502: adc #$01

.page 175
    STA $8b                 ; 6502: sta $008b
    CLC                     ; 6502: clc
    ADC #$01                ; 6502: adc #$01
    STA $8b                 ; 6502: sta $008b

.page 176
    CLC                     ; 6502: clc
    ADC #$01                ; 6502: adc #$01
    STA $8b                 ; 6502: sta $008b
    LDA $50                 ; 6502: lda $0050

.page 177
    EOR $8a                 ; 6502: eor $008a
    STA $50                 ; 6502: sta $0050
    LDA $51                 ; 6502: lda $0051
    CLC                     ; 6502: clc

.page 178
    ADC $8b                 ; 6502: adc $008b
    STA $51                 ; 6502: sta $0051
    LDA $52                 ; 6502: lda $0052
    ORA $83                 ; 6502: ora $0083

.page 179
    STA $52                 ; 6502: sta $0052
    LDA $53                 ; 6502: lda $0053
    AND #$FE                ; 6502: and #$FE
    STA $53                 ; 6502: sta $0053

.page 180
    HLT                     ; 6502: rts (rewritten -> HLT)
