; auto-generated by translate_6502.py
; full pipeline: cc65 -> translate_6502 -> ocpu_asm
    .data $0040            ; segment DATA
    .byte $0C
    .byte $2C
    .byte $5B
    .byte $03
    .byte $4D
    .byte $12
    .byte $C8
    .byte $05
    .byte $42
    .byte $63
    .byte $65
    .byte $2A
    .byte $58
    .byte $01
    .byte $FA
    .byte $11
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .data $0080            ; segment BSS
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00
    .byte $00

.page 0
_main:
    LDA #$00                ; 6502: lda #$00
    STA $80                 ; 6502: sta $0080
    STA $81                 ; 6502: sta $0081
    STA $82                 ; 6502: sta $0082
    STA $83                 ; 6502: sta $0083
    STA $88                 ; 6502: sta $0088
    STA $89                 ; 6502: sta $0089
    STA $8a                 ; 6502: sta $008a

.page 1
    STA $8b                 ; 6502: sta $008b
    STA $8c                 ; 6502: sta $008c
    STA $86                 ; 6502: sta $0086
    LDA #$FF                ; 6502: lda #$FF
    STA $87                 ; 6502: sta $0087
    LDA $40                 ; 6502: lda $0040
    STA $8d                 ; 6502: sta $008d
    LDA $41                 ; 6502: lda $0041

.page 2
    STA $8e                 ; 6502: sta $008e
    LDA $42                 ; 6502: lda $0042
    STA $8f                 ; 6502: sta $008f
    LDA $43                 ; 6502: lda $0043
    STA $90                 ; 6502: sta $0090
    LDA $44                 ; 6502: lda $0044
    STA $91                 ; 6502: sta $0091
    LDA $45                 ; 6502: lda $0045

.page 3
    STA $92                 ; 6502: sta $0092
    LDA $46                 ; 6502: lda $0046
    STA $93                 ; 6502: sta $0093
    LDA $47                 ; 6502: lda $0047
    STA $94                 ; 6502: sta $0094
    LDA $80                 ; 6502: lda $0080
    CLC                     ; 6502: clc
    ADC $8d                 ; 6502: adc $008d

.page 4
    STA $80                 ; 6502: sta $0080
    CLC                     ; 6502: clc
    ADC $8e                 ; 6502: adc $008e
    STA $80                 ; 6502: sta $0080
    CLC                     ; 6502: clc
    ADC $8f                 ; 6502: adc $008f
    STA $80                 ; 6502: sta $0080
    CLC                     ; 6502: clc

.page 5
    ADC $90                 ; 6502: adc $0090
    STA $80                 ; 6502: sta $0080
    CLC                     ; 6502: clc
    ADC $91                 ; 6502: adc $0091
    STA $80                 ; 6502: sta $0080
    CLC                     ; 6502: clc
    ADC $92                 ; 6502: adc $0092
    STA $80                 ; 6502: sta $0080

.page 6
    CLC                     ; 6502: clc
    ADC $93                 ; 6502: adc $0093
    STA $80                 ; 6502: sta $0080
    CLC                     ; 6502: clc
    ADC $94                 ; 6502: adc $0094
    STA $80                 ; 6502: sta $0080
    EOR $48                 ; 6502: eor $0048
    STA $80                 ; 6502: sta $0080

.page 7
    EOR $49                 ; 6502: eor $0049
    STA $80                 ; 6502: sta $0080
    EOR $4a                 ; 6502: eor $004a
    STA $80                 ; 6502: sta $0080
    EOR $4b                 ; 6502: eor $004b
    STA $80                 ; 6502: sta $0080
    EOR $4c                 ; 6502: eor $004c
    STA $80                 ; 6502: sta $0080

.page 8
    EOR $4d                 ; 6502: eor $004d
    STA $80                 ; 6502: sta $0080
    EOR $4e                 ; 6502: eor $004e
    STA $80                 ; 6502: sta $0080
    EOR $4f                 ; 6502: eor $004f
    STA $80                 ; 6502: sta $0080
    LDA $8d                 ; 6502: lda $008d
    CMP $86                 ; 6502: cmp $0086

.page 9
    BCC L004F               ; 6502: bcc L004F
    BEQ L004F               ; 6502: beq L004F
    STA $86                 ; 6502: sta $0086
L004F:
    LDA $8e                 ; 6502: lda $008e
    CMP $86                 ; 6502: cmp $0086
    BCS __brfix_4f     ; (auto-inverted, cross-page BCC -> L0050)
    FARJMP $0b        ; (auto-bridge)
__brfix_4f:
    NOP        ; no room for branch bridge

.page 10
    BNE __brfix_50     ; (auto-inverted, cross-page BEQ -> L0050)
    FARJMP $0b        ; (auto-bridge)
__brfix_50:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 11
L0050:
    LDA $8f                 ; 6502: lda $008f
    CMP $86                 ; 6502: cmp $0086
    BCC L0051               ; 6502: bcc L0051
    BEQ L0051               ; 6502: beq L0051
    STA $86                 ; 6502: sta $0086
L0051:
    LDA $90                 ; 6502: lda $0090
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge

.page 12
    BCS __brfix_5b     ; (auto-inverted, cross-page BCC -> L0052)
    FARJMP $0d        ; (auto-bridge)
__brfix_5b:
    BNE __brfix_5c     ; (auto-inverted, cross-page BEQ -> L0052)
    FARJMP $0d        ; (auto-bridge)
__brfix_5c:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 13
L0052:
    LDA $91                 ; 6502: lda $0091
    CMP $86                 ; 6502: cmp $0086
    BCC L0053               ; 6502: bcc L0053
    BEQ L0053               ; 6502: beq L0053
    STA $86                 ; 6502: sta $0086
L0053:
    LDA $92                 ; 6502: lda $0092
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge

.page 14
    BCS __brfix_67     ; (auto-inverted, cross-page BCC -> L0054)
    FARJMP $0f        ; (auto-bridge)
__brfix_67:
    BNE __brfix_68     ; (auto-inverted, cross-page BEQ -> L0054)
    FARJMP $0f        ; (auto-bridge)
__brfix_68:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 15
L0054:
    LDA $93                 ; 6502: lda $0093
    CMP $86                 ; 6502: cmp $0086
    BCC L0055               ; 6502: bcc L0055
    BEQ L0055               ; 6502: beq L0055
    STA $86                 ; 6502: sta $0086
L0055:
    LDA $94                 ; 6502: lda $0094
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge

.page 16
    BCS __brfix_73     ; (auto-inverted, cross-page BCC -> L0056)
    FARJMP $11        ; (auto-bridge)
__brfix_73:
    BNE __brfix_74     ; (auto-inverted, cross-page BEQ -> L0056)
    FARJMP $11        ; (auto-bridge)
__brfix_74:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 17
L0056:
    LDA $48                 ; 6502: lda $0048
    CMP $86                 ; 6502: cmp $0086
    BCC L0057               ; 6502: bcc L0057
    BEQ L0057               ; 6502: beq L0057
    STA $86                 ; 6502: sta $0086
L0057:
    LDA $49                 ; 6502: lda $0049
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge

.page 18
    BCS __brfix_7f     ; (auto-inverted, cross-page BCC -> L0058)
    FARJMP $13        ; (auto-bridge)
__brfix_7f:
    BNE __brfix_80     ; (auto-inverted, cross-page BEQ -> L0058)
    FARJMP $13        ; (auto-bridge)
__brfix_80:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 19
L0058:
    LDA $4a                 ; 6502: lda $004a
    CMP $86                 ; 6502: cmp $0086
    BCC L0059               ; 6502: bcc L0059
    BEQ L0059               ; 6502: beq L0059
    STA $86                 ; 6502: sta $0086
L0059:
    LDA $4b                 ; 6502: lda $004b
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge

.page 20
    BCS __brfix_8b     ; (auto-inverted, cross-page BCC -> L005A)
    FARJMP $15        ; (auto-bridge)
__brfix_8b:
    BNE __brfix_8c     ; (auto-inverted, cross-page BEQ -> L005A)
    FARJMP $15        ; (auto-bridge)
__brfix_8c:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 21
L005A:
    LDA $4c                 ; 6502: lda $004c
    CMP $86                 ; 6502: cmp $0086
    BCC L005B               ; 6502: bcc L005B
    BEQ L005B               ; 6502: beq L005B
    STA $86                 ; 6502: sta $0086
L005B:
    LDA $4d                 ; 6502: lda $004d
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge

.page 22
    BCS __brfix_97     ; (auto-inverted, cross-page BCC -> L005C)
    FARJMP $17        ; (auto-bridge)
__brfix_97:
    BNE __brfix_98     ; (auto-inverted, cross-page BEQ -> L005C)
    FARJMP $17        ; (auto-bridge)
__brfix_98:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 23
L005C:
    LDA $4e                 ; 6502: lda $004e
    CMP $86                 ; 6502: cmp $0086
    BCC L005D               ; 6502: bcc L005D
    BEQ L005D               ; 6502: beq L005D
    STA $86                 ; 6502: sta $0086
L005D:
    LDA $4f                 ; 6502: lda $004f
    CMP $86                 ; 6502: cmp $0086
    NOP        ; no room for branch bridge

.page 24
    BCS __brfix_a3     ; (auto-inverted, cross-page BCC -> L005E)
    FARJMP $19        ; (auto-bridge)
__brfix_a3:
    BNE __brfix_a4     ; (auto-inverted, cross-page BEQ -> L005E)
    FARJMP $19        ; (auto-bridge)
__brfix_a4:
    STA $86                 ; 6502: sta $0086
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 25
L005E:
    LDA $8d                 ; 6502: lda $008d
    CMP $87                 ; 6502: cmp $0087
    BCS L005F               ; 6502: bcs L005F
    STA $87                 ; 6502: sta $0087
L005F:
    LDA $8e                 ; 6502: lda $008e
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 26
    BCC __brfix_ae     ; (auto-inverted, cross-page BCS -> L0060)
    FARJMP $1b        ; (auto-bridge)
__brfix_ae:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 27
L0060:
    LDA $8f                 ; 6502: lda $008f
    CMP $87                 ; 6502: cmp $0087
    BCS L0061               ; 6502: bcs L0061
    STA $87                 ; 6502: sta $0087
L0061:
    LDA $90                 ; 6502: lda $0090
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 28
    BCC __brfix_b8     ; (auto-inverted, cross-page BCS -> L0062)
    FARJMP $1d        ; (auto-bridge)
__brfix_b8:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 29
L0062:
    LDA $91                 ; 6502: lda $0091
    CMP $87                 ; 6502: cmp $0087
    BCS L0063               ; 6502: bcs L0063
    STA $87                 ; 6502: sta $0087
L0063:
    LDA $92                 ; 6502: lda $0092
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 30
    BCC __brfix_c2     ; (auto-inverted, cross-page BCS -> L0064)
    FARJMP $1f        ; (auto-bridge)
__brfix_c2:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 31
L0064:
    LDA $93                 ; 6502: lda $0093
    CMP $87                 ; 6502: cmp $0087
    BCS L0065               ; 6502: bcs L0065
    STA $87                 ; 6502: sta $0087
L0065:
    LDA $94                 ; 6502: lda $0094
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 32
    BCC __brfix_cc     ; (auto-inverted, cross-page BCS -> L0066)
    FARJMP $21        ; (auto-bridge)
__brfix_cc:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 33
L0066:
    LDA $48                 ; 6502: lda $0048
    CMP $87                 ; 6502: cmp $0087
    BCS L0067               ; 6502: bcs L0067
    STA $87                 ; 6502: sta $0087
L0067:
    LDA $49                 ; 6502: lda $0049
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 34
    BCC __brfix_d6     ; (auto-inverted, cross-page BCS -> L0068)
    FARJMP $23        ; (auto-bridge)
__brfix_d6:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 35
L0068:
    LDA $4a                 ; 6502: lda $004a
    CMP $87                 ; 6502: cmp $0087
    BCS L0069               ; 6502: bcs L0069
    STA $87                 ; 6502: sta $0087
L0069:
    LDA $4b                 ; 6502: lda $004b
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 36
    BCC __brfix_e0     ; (auto-inverted, cross-page BCS -> L006A)
    FARJMP $25        ; (auto-bridge)
__brfix_e0:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 37
L006A:
    LDA $4c                 ; 6502: lda $004c
    CMP $87                 ; 6502: cmp $0087
    BCS L006B               ; 6502: bcs L006B
    STA $87                 ; 6502: sta $0087
L006B:
    LDA $4d                 ; 6502: lda $004d
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 38
    BCC __brfix_ea     ; (auto-inverted, cross-page BCS -> L006C)
    FARJMP $27        ; (auto-bridge)
__brfix_ea:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 39
L006C:
    LDA $4e                 ; 6502: lda $004e
    CMP $87                 ; 6502: cmp $0087
    BCS L006D               ; 6502: bcs L006D
    STA $87                 ; 6502: sta $0087
L006D:
    LDA $4f                 ; 6502: lda $004f
    CMP $87                 ; 6502: cmp $0087
    NOP        ; no room for branch bridge
    NOP        ; no room for branch bridge

.page 40
    BCC __brfix_f4     ; (auto-inverted, cross-page BCS -> L006E)
    FARJMP $29        ; (auto-bridge)
__brfix_f4:
    STA $87                 ; 6502: sta $0087
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 41
L006E:
    LDA $8d                 ; 6502: lda $008d
    CMP #$65                ; 6502: cmp #$65
    BCC L006F               ; 6502: bcc L006F
    LDA $81                 ; 6502: lda $0081
    CLC                     ; 6502: clc
    ADC #$01                ; 6502: adc #$01
    STA $81                 ; 6502: sta $0081
L006F:
    LDA $8e                 ; 6502: lda $008e

.page 42
    CMP #$65                ; 6502: cmp #$65
    BCC L0070               ; 6502: bcc L0070
    LDA $81                 ; 6502: lda $0081
    CLC                     ; 6502: clc
    ADC #$01                ; 6502: adc #$01
    STA $81                 ; 6502: sta $0081
L0070:
    LDA $8f                 ; 6502: lda $008f
    CMP #$65                ; 6502: cmp #$65

.page 43
    BCC L0071               ; 6502: bcc L0071
    LDA $81                 ; 6502: lda $0081
    CLC                     ; 6502: clc
    ADC #$01                ; 6502: adc #$01
    STA $81                 ; 6502: sta $0081
L0071:
    LDA $90                 ; 6502: lda $0090
    CMP #$65                ; 6502: cmp #$65
    NOP        ; no room for branch bridge

.page 44
    BCS __brfix_111     ; (auto-inverted, cross-page BCC -> L0072)
    FARJMP $2d        ; (auto-bridge)
__brfix_111:
    LDA $81                 ; 6502: lda $0081
    CLC                     ; 6502: clc
    ADC #$01                ; 6502: adc #$01
    STA $81                 ; 6502: sta $0081
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 45
L0072:
    LDA $4a                 ; 6502: lda $004a
    CMP #$79                ; 6502: cmp #$79
    BCC L0073               ; 6502: bcc L0073
    LDA $81                 ; 6502: lda $0081
    CLC                     ; 6502: clc
    ADC #$01                ; 6502: adc #$01
    STA $81                 ; 6502: sta $0081
L0073:
    LDA $4e                 ; 6502: lda $004e

.page 46
    CMP #$C9                ; 6502: cmp #$C9
    BCC L0074               ; 6502: bcc L0074
    LDA $82                 ; 6502: lda $0082
    CLC                     ; 6502: clc
    ADC #$01                ; 6502: adc #$01
    STA $82                 ; 6502: sta $0082
L0074:
    LDA $46                 ; 6502: lda $0046
    CMP #$B5                ; 6502: cmp #$B5

.page 47
    BCS __brfix_129     ; (auto-inverted, cross-page BCC -> L0075)
    FARJMP $31        ; (auto-bridge)
__brfix_129:
    LDA $82                 ; 6502: lda $0082
    CLC                     ; 6502: clc
    ADC #$01                ; 6502: adc #$01
    STA $82                 ; 6502: sta $0082
    LDA $83                 ; 6502: lda $0083
    ORA #$01                ; 6502: ora #$01

.page 48
    FARJMP $32        ; (rewritten from JMP L004B; cross-page)
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 49
L0075:
    LDA $83                 ; 6502: lda $0083
    EOR #$02                ; 6502: eor #$02
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 50
L004B:
    STA $83                 ; 6502: sta $0083
    LDA $86                 ; 6502: lda $0086
    CMP #$F1                ; 6502: cmp #$F1
    BCS __brfix_138     ; (auto-inverted, cross-page BCC -> L0076)
    FARJMP $33        ; (auto-bridge)
__brfix_138:
    LDA $8c                 ; 6502: lda $008c
    ORA #$80                ; 6502: ora #$80
    FARJMP $34        ; (rewritten from JMP L004C; cross-page)

.page 51
L0076:
    LDA $8c                 ; 6502: lda $008c
    ORA #$01                ; 6502: ora #$01
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 52
L004C:
    STA $8c                 ; 6502: sta $008c
    LDA $87                 ; 6502: lda $0087
    CMP #$05                ; 6502: cmp #$05
    BCC __brfix_143     ; (auto-inverted, cross-page BCS -> L0077)
    FARJMP $35        ; (auto-bridge)
__brfix_143:
    LDA $8c                 ; 6502: lda $008c
    ORA #$40                ; 6502: ora #$40
    STA $8c                 ; 6502: sta $008c

.page 53
L0077:
    LDA $89                 ; 6502: lda $0089
    EOR $40                 ; 6502: eor $0040
    STA $89                 ; 6502: sta $0089
    EOR $41                 ; 6502: eor $0041
    STA $89                 ; 6502: sta $0089
    EOR $42                 ; 6502: eor $0042
    STA $89                 ; 6502: sta $0089
    EOR $43                 ; 6502: eor $0043

.page 54
    STA $89                 ; 6502: sta $0089
    EOR $44                 ; 6502: eor $0044
    STA $89                 ; 6502: sta $0089
    EOR $45                 ; 6502: eor $0045
    STA $89                 ; 6502: sta $0089
    EOR $46                 ; 6502: eor $0046
    STA $89                 ; 6502: sta $0089
    EOR $47                 ; 6502: eor $0047

.page 55
    STA $89                 ; 6502: sta $0089
    LDA #$00                ; 6502: lda #$00
    STA $88                 ; 6502: sta $0088
    CLC                     ; 6502: clc
    LDA $40                 ; 6502: lda $0040
    STA $88                 ; 6502: sta $0088
    CLC                     ; 6502: clc
    ADC $41                 ; 6502: adc $0041

.page 56
    STA $88                 ; 6502: sta $0088
    CLC                     ; 6502: clc
    ADC $42                 ; 6502: adc $0042
    STA $88                 ; 6502: sta $0088
    CLC                     ; 6502: clc
    ADC $43                 ; 6502: adc $0043
    STA $88                 ; 6502: sta $0088
    CLC                     ; 6502: clc

.page 57
    ADC $44                 ; 6502: adc $0044
    STA $88                 ; 6502: sta $0088
    CLC                     ; 6502: clc
    ADC $45                 ; 6502: adc $0045
    STA $88                 ; 6502: sta $0088
    CLC                     ; 6502: clc
    ADC $46                 ; 6502: adc $0046
    STA $88                 ; 6502: sta $0088

.page 58
    CLC                     ; 6502: clc
    ADC $47                 ; 6502: adc $0047
    STA $88                 ; 6502: sta $0088
    CLC                     ; 6502: clc
    ADC #$08                ; 6502: adc #$08
    STA $88                 ; 6502: sta $0088
    LDA $80                 ; 6502: lda $0080
    STA $50                 ; 6502: sta $0050

.page 59
    LDA $81                 ; 6502: lda $0081
    STA $51                 ; 6502: sta $0051
    LDA $82                 ; 6502: lda $0082
    STA $52                 ; 6502: sta $0052
    LDA $86                 ; 6502: lda $0086
    STA $53                 ; 6502: sta $0053
    LDA $87                 ; 6502: lda $0087
    STA $54                 ; 6502: sta $0054

.page 60
    LDA $89                 ; 6502: lda $0089
    STA $55                 ; 6502: sta $0055
    LDA $88                 ; 6502: lda $0088
    STA $56                 ; 6502: sta $0056
    LDA $8c                 ; 6502: lda $008c
    STA $57                 ; 6502: sta $0057
    LDA $40                 ; 6502: lda $0040
    EOR $80                 ; 6502: eor $0080

.page 61
    STA $58                 ; 6502: sta $0058
    LDA $41                 ; 6502: lda $0041
    EOR $80                 ; 6502: eor $0080
    STA $59                 ; 6502: sta $0059
    LDA $42                 ; 6502: lda $0042
    EOR $80                 ; 6502: eor $0080
    STA $5a                 ; 6502: sta $005a
    LDA $43                 ; 6502: lda $0043

.page 62
    EOR $80                 ; 6502: eor $0080
    STA $5b                 ; 6502: sta $005b
    LDA $44                 ; 6502: lda $0044
    CLC                     ; 6502: clc
    ADC $81                 ; 6502: adc $0081
    STA $5c                 ; 6502: sta $005c
    LDA $45                 ; 6502: lda $0045
    CLC                     ; 6502: clc

.page 63
    ADC $81                 ; 6502: adc $0081
    STA $5d                 ; 6502: sta $005d
    LDA $46                 ; 6502: lda $0046
    CLC                     ; 6502: clc
    ADC $81                 ; 6502: adc $0081
    STA $5e                 ; 6502: sta $005e
    LDA $47                 ; 6502: lda $0047
    CLC                     ; 6502: clc

.page 64
    ADC $81                 ; 6502: adc $0081
    STA $5f                 ; 6502: sta $005f
    LDA $48                 ; 6502: lda $0048
    ORA $83                 ; 6502: ora $0083
    STA $60                 ; 6502: sta $0060
    LDA $49                 ; 6502: lda $0049
    ORA $83                 ; 6502: ora $0083
    STA $61                 ; 6502: sta $0061

.page 65
    LDA $4a                 ; 6502: lda $004a
    ORA $83                 ; 6502: ora $0083
    STA $62                 ; 6502: sta $0062
    LDA $4b                 ; 6502: lda $004b
    ORA $83                 ; 6502: ora $0083
    STA $63                 ; 6502: sta $0063
    LDA $4c                 ; 6502: lda $004c
    AND #$7F                ; 6502: and #$7F

.page 66
    STA $64                 ; 6502: sta $0064
    LDA $4d                 ; 6502: lda $004d
    AND #$7F                ; 6502: and #$7F
    STA $65                 ; 6502: sta $0065
    LDA $4e                 ; 6502: lda $004e
    AND #$7F                ; 6502: and #$7F
    STA $66                 ; 6502: sta $0066
    LDA $4f                 ; 6502: lda $004f

.page 67
    AND #$7F                ; 6502: and #$7F
    STA $67                 ; 6502: sta $0067
    LDA $50                 ; 6502: lda $0050
    EOR $58                 ; 6502: eor $0058
    STA $68                 ; 6502: sta $0068
    LDA $51                 ; 6502: lda $0051
    EOR $59                 ; 6502: eor $0059
    STA $69                 ; 6502: sta $0069

.page 68
    LDA $52                 ; 6502: lda $0052
    EOR $5a                 ; 6502: eor $005a
    STA $6a                 ; 6502: sta $006a
    LDA $53                 ; 6502: lda $0053
    EOR $5b                 ; 6502: eor $005b
    STA $6b                 ; 6502: sta $006b
    LDA $54                 ; 6502: lda $0054
    CLC                     ; 6502: clc

.page 69
    ADC $5c                 ; 6502: adc $005c
    STA $6c                 ; 6502: sta $006c
    LDA $55                 ; 6502: lda $0055
    CLC                     ; 6502: clc
    ADC $5d                 ; 6502: adc $005d
    STA $6d                 ; 6502: sta $006d
    LDA $56                 ; 6502: lda $0056
    CLC                     ; 6502: clc

.page 70
    ADC $5e                 ; 6502: adc $005e
    STA $6e                 ; 6502: sta $006e
    LDA $57                 ; 6502: lda $0057
    CLC                     ; 6502: clc
    ADC $5f                 ; 6502: adc $005f
    STA $6f                 ; 6502: sta $006f
    LDA #$00                ; 6502: lda #$00
    STA $8a                 ; 6502: sta $008a

.page 71
    LDA $82                 ; 6502: lda $0082
    BEQ L0078               ; 6502: beq L0078
    LDA $8a                 ; 6502: lda $008a
    ORA #$80                ; 6502: ora #$80
    JMP L004D               ; 6502: jmp L004D
L0078:
    LDA $8a                 ; 6502: lda $008a
    ORA #$01                ; 6502: ora #$01
L004D:
    STA $8a                 ; 6502: sta $008a

.page 72
    LDA $81                 ; 6502: lda $0081
    CMP #$03                ; 6502: cmp #$03
    BCC L0079               ; 6502: bcc L0079
    LDA $8a                 ; 6502: lda $008a
    ORA #$40                ; 6502: ora #$40
    STA $8a                 ; 6502: sta $008a
L0079:
    LDA $80                 ; 6502: lda $0080
    NOP        ; no room for branch bridge

.page 73
    BEQ __brfix_1ea     ; (auto-inverted, cross-page BNE -> L007A)
    FARJMP $4a        ; (auto-bridge)
__brfix_1ea:
    LDA $8a                 ; 6502: lda $008a
    ORA #$20                ; 6502: ora #$20
    FARJMP $4b        ; (rewritten from JMP L004E; cross-page)
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 74
L007A:
    LDA $8a                 ; 6502: lda $008a
    EOR #$04                ; 6502: eor #$04
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0
    NOP        ; align next label to slot 0

.page 75
L004E:
    STA $8a                 ; 6502: sta $008a
    LDA #$00                ; 6502: lda #$00
    STA $8b                 ; 6502: sta $008b
    CLC                     ; 6502: clc
    LDA #$01                ; 6502: lda #$01
    STA $8b                 ; 6502: sta $008b
    CLC                     ; 6502: clc
    ADC #$01                ; 6502: adc #$01

.page 76
    STA $8b                 ; 6502: sta $008b
    CLC                     ; 6502: clc
    ADC #$01                ; 6502: adc #$01
    STA $8b                 ; 6502: sta $008b
    CLC                     ; 6502: clc
    ADC #$01                ; 6502: adc #$01
    STA $8b                 ; 6502: sta $008b
    CLC                     ; 6502: clc

.page 77
    ADC #$01                ; 6502: adc #$01
    STA $8b                 ; 6502: sta $008b
    CLC                     ; 6502: clc
    ADC #$01                ; 6502: adc #$01
    STA $8b                 ; 6502: sta $008b
    CLC                     ; 6502: clc
    ADC #$01                ; 6502: adc #$01
    STA $8b                 ; 6502: sta $008b

.page 78
    CLC                     ; 6502: clc
    ADC #$01                ; 6502: adc #$01
    STA $8b                 ; 6502: sta $008b
    LDA $50                 ; 6502: lda $0050
    EOR $8a                 ; 6502: eor $008a
    STA $50                 ; 6502: sta $0050
    LDA $51                 ; 6502: lda $0051
    CLC                     ; 6502: clc

.page 79
    ADC $8b                 ; 6502: adc $008b
    STA $51                 ; 6502: sta $0051
    LDA $52                 ; 6502: lda $0052
    ORA $83                 ; 6502: ora $0083
    STA $52                 ; 6502: sta $0052
    LDA $53                 ; 6502: lda $0053
    AND #$FE                ; 6502: and #$FE
    STA $53                 ; 6502: sta $0053

.page 80
    HLT                     ; 6502: rts (rewritten -> HLT)
