;
; File generated by cc65 v 2.19 - Git b4e66ea
;
	.fopt		compiler,"cc65 v 2.19 - Git b4e66ea"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	c_sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_sensors
	.export		_framebuffer
	.export		_checksum
	.export		_warnings
	.export		_errors
	.export		_state
	.export		_temp
	.export		_temp2
	.export		_max_value
	.export		_min_value
	.export		_average
	.export		_parity
	.export		_control
	.export		_counter
	.export		_status
	.export		_a0
	.export		_a1
	.export		_a2
	.export		_a3
	.export		_a4
	.export		_a5
	.export		_a6
	.export		_a7
	.export		_main

.segment	"DATA"

_sensors:
	.byte	$0C
	.byte	$2C
	.byte	$5B
	.byte	$03
	.byte	$4D
	.byte	$12
	.byte	$C8
	.byte	$05
	.byte	$42
	.byte	$63
	.byte	$65
	.byte	$2A
	.byte	$58
	.byte	$01
	.byte	$FA
	.byte	$11
_framebuffer:
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00

.segment	"BSS"

_checksum:
	.res	1,$00
_warnings:
	.res	1,$00
_errors:
	.res	1,$00
_state:
	.res	1,$00
_temp:
	.res	1,$00
_temp2:
	.res	1,$00
_max_value:
	.res	1,$00
_min_value:
	.res	1,$00
_average:
	.res	1,$00
_parity:
	.res	1,$00
_control:
	.res	1,$00
_counter:
	.res	1,$00
_status:
	.res	1,$00
_a0:
	.res	1,$00
_a1:
	.res	1,$00
_a2:
	.res	1,$00
_a3:
	.res	1,$00
_a4:
	.res	1,$00
_a5:
	.res	1,$00
_a6:
	.res	1,$00
_a7:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #$00
	sta     _checksum
	sta     _warnings
	sta     _errors
	sta     _state
	sta     _average
	sta     _parity
	sta     _control
	sta     _counter
	sta     _status
	sta     _max_value
	lda     #$FF
	sta     _min_value
	lda     _sensors
	sta     _a0
	lda     _sensors+1
	sta     _a1
	lda     _sensors+2
	sta     _a2
	lda     _sensors+3
	sta     _a3
	lda     _sensors+4
	sta     _a4
	lda     _sensors+5
	sta     _a5
	lda     _sensors+6
	sta     _a6
	lda     _sensors+7
	sta     _a7
	lda     _checksum
	clc
	adc     _a0
	sta     _checksum
	clc
	adc     _a1
	sta     _checksum
	clc
	adc     _a2
	sta     _checksum
	clc
	adc     _a3
	sta     _checksum
	clc
	adc     _a4
	sta     _checksum
	clc
	adc     _a5
	sta     _checksum
	clc
	adc     _a6
	sta     _checksum
	clc
	adc     _a7
	sta     _checksum
	eor     _sensors+8
	sta     _checksum
	eor     _sensors+9
	sta     _checksum
	eor     _sensors+10
	sta     _checksum
	eor     _sensors+11
	sta     _checksum
	eor     _sensors+12
	sta     _checksum
	eor     _sensors+13
	sta     _checksum
	eor     _sensors+14
	sta     _checksum
	eor     _sensors+15
	sta     _checksum
	lda     _a0
	cmp     _max_value
	bcc     L004F
	beq     L004F
	sta     _max_value
L004F:	lda     _a1
	cmp     _max_value
	bcc     L0050
	beq     L0050
	sta     _max_value
L0050:	lda     _a2
	cmp     _max_value
	bcc     L0051
	beq     L0051
	sta     _max_value
L0051:	lda     _a3
	cmp     _max_value
	bcc     L0052
	beq     L0052
	sta     _max_value
L0052:	lda     _a4
	cmp     _max_value
	bcc     L0053
	beq     L0053
	sta     _max_value
L0053:	lda     _a5
	cmp     _max_value
	bcc     L0054
	beq     L0054
	sta     _max_value
L0054:	lda     _a6
	cmp     _max_value
	bcc     L0055
	beq     L0055
	sta     _max_value
L0055:	lda     _a7
	cmp     _max_value
	bcc     L0056
	beq     L0056
	sta     _max_value
L0056:	lda     _sensors+8
	cmp     _max_value
	bcc     L0057
	beq     L0057
	sta     _max_value
L0057:	lda     _sensors+9
	cmp     _max_value
	bcc     L0058
	beq     L0058
	sta     _max_value
L0058:	lda     _sensors+10
	cmp     _max_value
	bcc     L0059
	beq     L0059
	sta     _max_value
L0059:	lda     _sensors+11
	cmp     _max_value
	bcc     L005A
	beq     L005A
	sta     _max_value
L005A:	lda     _sensors+12
	cmp     _max_value
	bcc     L005B
	beq     L005B
	sta     _max_value
L005B:	lda     _sensors+13
	cmp     _max_value
	bcc     L005C
	beq     L005C
	sta     _max_value
L005C:	lda     _sensors+14
	cmp     _max_value
	bcc     L005D
	beq     L005D
	sta     _max_value
L005D:	lda     _sensors+15
	cmp     _max_value
	bcc     L005E
	beq     L005E
	sta     _max_value
L005E:	lda     _a0
	cmp     _min_value
	bcs     L005F
	sta     _min_value
L005F:	lda     _a1
	cmp     _min_value
	bcs     L0060
	sta     _min_value
L0060:	lda     _a2
	cmp     _min_value
	bcs     L0061
	sta     _min_value
L0061:	lda     _a3
	cmp     _min_value
	bcs     L0062
	sta     _min_value
L0062:	lda     _a4
	cmp     _min_value
	bcs     L0063
	sta     _min_value
L0063:	lda     _a5
	cmp     _min_value
	bcs     L0064
	sta     _min_value
L0064:	lda     _a6
	cmp     _min_value
	bcs     L0065
	sta     _min_value
L0065:	lda     _a7
	cmp     _min_value
	bcs     L0066
	sta     _min_value
L0066:	lda     _sensors+8
	cmp     _min_value
	bcs     L0067
	sta     _min_value
L0067:	lda     _sensors+9
	cmp     _min_value
	bcs     L0068
	sta     _min_value
L0068:	lda     _sensors+10
	cmp     _min_value
	bcs     L0069
	sta     _min_value
L0069:	lda     _sensors+11
	cmp     _min_value
	bcs     L006A
	sta     _min_value
L006A:	lda     _sensors+12
	cmp     _min_value
	bcs     L006B
	sta     _min_value
L006B:	lda     _sensors+13
	cmp     _min_value
	bcs     L006C
	sta     _min_value
L006C:	lda     _sensors+14
	cmp     _min_value
	bcs     L006D
	sta     _min_value
L006D:	lda     _sensors+15
	cmp     _min_value
	bcs     L006E
	sta     _min_value
L006E:	lda     _a0
	cmp     #$65
	bcc     L006F
	lda     _warnings
	clc
	adc     #$01
	sta     _warnings
L006F:	lda     _a1
	cmp     #$65
	bcc     L0070
	lda     _warnings
	clc
	adc     #$01
	sta     _warnings
L0070:	lda     _a2
	cmp     #$65
	bcc     L0071
	lda     _warnings
	clc
	adc     #$01
	sta     _warnings
L0071:	lda     _a3
	cmp     #$65
	bcc     L0072
	lda     _warnings
	clc
	adc     #$01
	sta     _warnings
L0072:	lda     _sensors+10
	cmp     #$79
	bcc     L0073
	lda     _warnings
	clc
	adc     #$01
	sta     _warnings
L0073:	lda     _sensors+14
	cmp     #$C9
	bcc     L0074
	lda     _errors
	clc
	adc     #$01
	sta     _errors
L0074:	lda     _sensors+6
	cmp     #$B5
	bcc     L0075
	lda     _errors
	clc
	adc     #$01
	sta     _errors
	lda     _state
	ora     #$01
	jmp     L004B
L0075:	lda     _state
	eor     #$02
L004B:	sta     _state
	lda     _max_value
	cmp     #$F1
	bcc     L0076
	lda     _status
	ora     #$80
	jmp     L004C
L0076:	lda     _status
	ora     #$01
L004C:	sta     _status
	lda     _min_value
	cmp     #$05
	bcs     L0077
	lda     _status
	ora     #$40
	sta     _status
L0077:	lda     _parity
	eor     _sensors
	sta     _parity
	eor     _sensors+1
	sta     _parity
	eor     _sensors+2
	sta     _parity
	eor     _sensors+3
	sta     _parity
	eor     _sensors+4
	sta     _parity
	eor     _sensors+5
	sta     _parity
	eor     _sensors+6
	sta     _parity
	eor     _sensors+7
	sta     _parity
	lda     #$00
	sta     _average
	clc
	lda     _sensors
	sta     _average
	clc
	adc     _sensors+1
	sta     _average
	clc
	adc     _sensors+2
	sta     _average
	clc
	adc     _sensors+3
	sta     _average
	clc
	adc     _sensors+4
	sta     _average
	clc
	adc     _sensors+5
	sta     _average
	clc
	adc     _sensors+6
	sta     _average
	clc
	adc     _sensors+7
	sta     _average
	clc
	adc     #$08
	sta     _average
	lda     _checksum
	sta     _framebuffer
	lda     _warnings
	sta     _framebuffer+1
	lda     _errors
	sta     _framebuffer+2
	lda     _max_value
	sta     _framebuffer+3
	lda     _min_value
	sta     _framebuffer+4
	lda     _parity
	sta     _framebuffer+5
	lda     _average
	sta     _framebuffer+6
	lda     _status
	sta     _framebuffer+7
	lda     _sensors
	eor     _checksum
	sta     _framebuffer+8
	lda     _sensors+1
	eor     _checksum
	sta     _framebuffer+9
	lda     _sensors+2
	eor     _checksum
	sta     _framebuffer+10
	lda     _sensors+3
	eor     _checksum
	sta     _framebuffer+11
	lda     _sensors+4
	clc
	adc     _warnings
	sta     _framebuffer+12
	lda     _sensors+5
	clc
	adc     _warnings
	sta     _framebuffer+13
	lda     _sensors+6
	clc
	adc     _warnings
	sta     _framebuffer+14
	lda     _sensors+7
	clc
	adc     _warnings
	sta     _framebuffer+15
	lda     _sensors+8
	ora     _state
	sta     _framebuffer+16
	lda     _sensors+9
	ora     _state
	sta     _framebuffer+17
	lda     _sensors+10
	ora     _state
	sta     _framebuffer+18
	lda     _sensors+11
	ora     _state
	sta     _framebuffer+19
	lda     _sensors+12
	and     #$7F
	sta     _framebuffer+20
	lda     _sensors+13
	and     #$7F
	sta     _framebuffer+21
	lda     _sensors+14
	and     #$7F
	sta     _framebuffer+22
	lda     _sensors+15
	and     #$7F
	sta     _framebuffer+23
	lda     _framebuffer
	eor     _framebuffer+8
	sta     _framebuffer+24
	lda     _framebuffer+1
	eor     _framebuffer+9
	sta     _framebuffer+25
	lda     _framebuffer+2
	eor     _framebuffer+10
	sta     _framebuffer+26
	lda     _framebuffer+3
	eor     _framebuffer+11
	sta     _framebuffer+27
	lda     _framebuffer+4
	clc
	adc     _framebuffer+12
	sta     _framebuffer+28
	lda     _framebuffer+5
	clc
	adc     _framebuffer+13
	sta     _framebuffer+29
	lda     _framebuffer+6
	clc
	adc     _framebuffer+14
	sta     _framebuffer+30
	lda     _framebuffer+7
	clc
	adc     _framebuffer+15
	sta     _framebuffer+31
	lda     #$00
	sta     _control
	lda     _errors
	beq     L0078
	lda     _control
	ora     #$80
	jmp     L004D
L0078:	lda     _control
	ora     #$01
L004D:	sta     _control
	lda     _warnings
	cmp     #$03
	bcc     L0079
	lda     _control
	ora     #$40
	sta     _control
L0079:	lda     _checksum
	bne     L007A
	lda     _control
	ora     #$20
	jmp     L004E
L007A:	lda     _control
	eor     #$04
L004E:	sta     _control
	lda     #$00
	sta     _counter
	clc
	lda     #$01
	sta     _counter
	clc
	adc     #$01
	sta     _counter
	clc
	adc     #$01
	sta     _counter
	clc
	adc     #$01
	sta     _counter
	clc
	adc     #$01
	sta     _counter
	clc
	adc     #$01
	sta     _counter
	clc
	adc     #$01
	sta     _counter
	clc
	adc     #$01
	sta     _counter
	lda     _framebuffer
	eor     _control
	sta     _framebuffer
	lda     _framebuffer+1
	clc
	adc     _counter
	sta     _framebuffer+1
	lda     _framebuffer+2
	ora     _state
	sta     _framebuffer+2
	lda     _framebuffer+3
	and     #$FE
	sta     _framebuffer+3
	rts

.endproc

