#requires -version 5.1
<#
.SYNOPSIS
    run all ocpu cocotb validation tests.

.DESCRIPTION
    delegates to `make -B` inside test/. requires icarus verilog and a
    python environment with the packages in test/requirements.txt
    installed (cocotb >= 2.0).

.PARAMETER Gates
    if specified, runs gate-level simulation. requires
    test/gate_level_netlist.v to exist (copied in from openlane output).

.PARAMETER OneTest
    run only a single test function by name (e.g. -OneTest test_lda_imm).
    leave unset to run the whole suite.

.EXAMPLE
    pwsh tools\run_tests.ps1
    pwsh tools\run_tests.ps1 -OneTest test_indy
    pwsh tools\run_tests.ps1 -Gates
#>
[CmdletBinding()]
param(
    [switch]$Gates,
    [string]$OneTest = ""
)

$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$testDir  = Join-Path $repoRoot "test"

if (-not (Test-Path (Join-Path $testDir "Makefile"))) {
    throw "test/Makefile not found; expected at $testDir"
}

# the assembler-emitted .hex files are regenerated by cocotb at runtime via
# import ocpu_asm; nothing to pre-build here.

Push-Location $testDir
try {
    $makeArgs = @("-B")
    if ($Gates) { $makeArgs += "GATES=yes" }
    if ($OneTest) { $env:COCOTB_TESTCASE = $OneTest }

    Write-Host "==> running: make $($makeArgs -join ' ')" -ForegroundColor Cyan
    & make @makeArgs
    if ($LASTEXITCODE -ne 0) {
        throw "cocotb test run failed with exit code $LASTEXITCODE"
    }

    # locate the results.xml that cocotb drops next to the simulator output.
    $results = Get-ChildItem -Path "sim_build" -Recurse -Filter "results.xml" -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($results) {
        Write-Host "==> results: $($results.FullName)" -ForegroundColor Green
    }
}
finally {
    if ($OneTest) { Remove-Item env:COCOTB_TESTCASE -ErrorAction SilentlyContinue }
    Pop-Location
}
